title = " Блогът на Ивайло Кузев"
baseURL = "http://example.org/"
languageCode = "bg"
theme = "hugo-zen"
copyright = "Ивайло Кузев, 2012-2017"
DisqusShortname = "ivkuzev"

[params]
  logo   = "/images/profile.jpg"
  github = "https://github.com/ivoarch"
  email  = "ivkuzev@gmail.com"
  RSSLink = "/index.xml"
  analytics = "UA-41596463-2"
